config/routes.rb
Fitnote::Application.routes.draw do
  root to: 'static_pages#root'

  resources :users
  resource :session

  namespace :api, defaults: {format: :json} do
    resources :notebooks
    resources :notes
    resources :tags
    resources :taggings
  end
end

# , defaults: {format: :json}

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :username, :password_digest, :session_token, presence: true
  validates :email, :username, uniqueness: true
  validates :password, length: { minimum: 6, allow_nil: true }

  attr_reader :password

  after_initialize :ensure_session_token
  before_save :ensure_notebook

  has_many(
    :notebooks,
    class_name: 'Notebook',
    foreign_key: :owner_id,
    primary_key: :id
  )

  has_many(
    :tags,
    class_name: "Tag",
    foreign_key: :user_id,
    primary_key: :id,
    dependent: :destroy
  )

  has_many(
    :notes,
    through: :notebooks,
    source: :notes
  )

  def ensure_notebook
    if self.notebooks.empty?
      self.notebooks.build(:name => "First Notebook")
    end
  end

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token!
    self.session_token = SecureRandom.urlsafe_base64(16)
    self.save!
    self.session_token
  end

  private
  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64(16)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to root_url
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:password, :username, :email)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/new.html.erb
<div id="sign-in-form">
  <h1>Fitness Companion</h1>
  <p>Fitnote makes your fitness manageable by letting you collect and access everything that matters.</p>
  <form class="demo" action="<%= session_url %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <input type="hidden" name="user[email]" value="charlie@gmail.com">
    <input type="hidden" name="user[password]" value="password">
    <input type="submit" class="btn evernote-green" value="Try The Demo">
  </form>

  <p>- Or Sign Up -</p>

  <form class="form-horizontal sign-in" action="<%= users_url %>" method="post">
    <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <div class="form-group">
      <label for="inputUsername" class="col-sm-2 control-label"></label>
      <div class="col-sm-10">
        <input type="text" name="user[username]" class="form-control" id="inputUsername" placeholder="Username">
      </div>
    </div>

    <div class="form-group">
      <label for="inputEmail3" class="col-sm-2 control-label"></label>
      <div class="col-sm-10">
        <input type="email" name="user[email]" class="form-control" id="inputEmail3" placeholder="Email">
      </div>
    </div>
    <div class="form-group">
      <label for="inputPassword3" class="col-sm-2 control-label"></label>
      <div class="col-sm-10">
        <input type="password" name="user[password]" class="form-control" id="inputPassword3" placeholder="Password">
      </div>
    </div>

    <div class="form-group">
      <div class="sign-button col-sm-offset-2 col-sm-10">
        <button type="submit" class="btn evernote-green">Sign up</button>
      </div>
    </div>
  </form>
  <div>
    <a href="<%= new_session_url %>" class="sign-up-link">Click here to Sign In</a>
  </div>
</div>